name: Android App Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Install Go Mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0

      - name: Install Android NDK
        run: |
          yes | sdkmanager --install "ndk;25.2.9519653" # 替换版本号以安装所需版本的 NDK
          echo "export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_NDK_HOME:$PATH" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          $ANDROID_NDK_HOME/ndk-build --version

      - name: Build the app
        run: |
          gomobile build -target=android -o TeslaBlueboothKey.apk -androidapi 25 ./main.go

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: TeslaBlueboothKey.apk
          retention-days: 3
